### PR TITLE
User Setable ping breakpoints

### PR DESCRIPTION
**Pull request by Fesaa**
This change makes it possible for users to choose the breakpoints for ping colours. Changeable via the Mod Menu integration. 
I've chosen for the name "border" for these breakpoints, as I didn't come up with anything better. 
Current limitations is the name of the colour changers, as they won't update if you update the borders/breakpoints yourself. 
This change required YACL to be updated to 2.1.0! I've also changed the fabric-loom version, although I don't know if this was strictly needed.

Example

I've not changed the Mod Version, as I don't know how you handle that.

### CODE REVIEW

**Comment by TheKodeToad** [comment]
Hi, thanks for this contribution to the project! Do you think threshold would be a better word (I'm not asking you to implement this right away, just curious on what you think)?

**Comment by Fesaa** [comment]
Yes, I absolutely agree that border can and should be improved on. Threshold is certainly a good one, I'll sleep on it and see if I find a better one tomorrow 🙂 
If not, can implement tomorrow as well.

**Comment by TheKodeToad** [comment]
Maybe these limitations with the colour labels could be worked around by reverting to the old option names: Default Ping Color, Level 1 Color etc.

**Comment by Fesaa** [comment]
We could do this, or we could open the menu again on save but remade with null as the parent screen, so it updates on each save. I personally like to have the numbers still be displayed in them.

**Comment by TheKodeToad** [comment]
> We could do this, or we could open the menu again on save but remade with null as the parent screen, so it updates on each save. I personally like to have the numbers still be displayed in them.

This will reset scrolling unfortunately.

**Comment by Fesaa** [comment]
I see, will change it it what you said before. Would be consistent naming as well.

**Comment by TheKodeToad** [comment]
It seems the US translation file uses the UK spellings of colour. Color should be in en_us.json, and colour in en_gb.json.

**Comment by TheKodeToad** [comment]
Looks good! Sorry for the delay, again. I've been procrastinating.

**Pull request merged**
